import type { Meta, StoryObj } from '@storybook/react';
import { fn } from '@storybook/test';
import { SchemaPanel } from './SchemaPanel';

const SAMPLE_SOURCE = `// Generated by Contexture from allotment.contexture.json. Do not edit.
import { z } from 'zod';
import { Email } from '@contexture/runtime/common';

export const Gardener = z.object({
  name: z.string().min(1),
  email: Email,
});

export const Plot = z.object({
  id: z.string().uuid(),
  sizeSqm: z.number().positive(),
  gardener: z.lazy(() => Gardener),
});
`;

const meta = {
  title: 'Components/SchemaPanel',
  component: SchemaPanel,
  args: {
    onCopy: fn(),
  },
  parameters: {
    layout: 'fullscreen',
  },
  decorators: [
    (Story) => (
      <div style={{ height: '600px', width: '480px', display: 'flex' }}>
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof SchemaPanel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Populated: Story = {
  args: {
    zodSource: SAMPLE_SOURCE,
    isEmpty: false,
    error: null,
    schemaFileName: 'allotment.schema.ts',
  },
};

export const Empty: Story = {
  args: {
    zodSource: '',
    isEmpty: true,
    error: null,
  },
};

export const ErrorState: Story = {
  args: {
    zodSource: '',
    isEmpty: false,
    error: "Unknown FieldType kind: 'frobnicate'",
  },
};
