/**
 * Emitter round-trip: every IR sidecar, when passed through the Zod
 * emitter, produces a source file that (a) declares each TypeDef as an
 * `export const <Name>`, (b) re-exports its inferred type, and (c) parses
 * the same fixture inputs the hand-written module would. The parity
 * test suite already covers the semantic parse equality per fixture;
 * this test fixes the surface-level emit contract (exports, header,
 * imports) so a regression in the emitter can't slip past.
 */

import { IR_BY_NAMESPACE, NAMESPACES } from '@contexture/stdlib/registry';
import { emit } from '@renderer/model/emit-zod';
import type { Schema } from '@renderer/model/ir';
import { describe, expect, it } from 'vitest';

for (const ns of NAMESPACES) {
  describe(`emit round-trip: ${ns}`, () => {
    const ir = IR_BY_NAMESPACE[ns] as unknown as Schema;
    const source = emit(ir, `packages/stdlib/src/${ns}.contexture.json`);

    it('starts with the generated-file header', () => {
      expect(source).toMatch(/^\/\/ Generated by Contexture from .*\. Do not edit\.\n/);
    });

    it(`imports zod`, () => {
      expect(source).toContain(`import { z } from 'zod';`);
    });

    it.each(ir.types.map((t) => t.name))(`exports %s`, (name) => {
      expect(source).toMatch(new RegExp(`\\bexport const ${name}\\b`));
      expect(source).toMatch(new RegExp(`\\bexport type ${name}\\b`));
    });
  });
}
