import { buildSaveBundle } from '@main/save-bundle';
import { DEFAULT_CHAT_HISTORY } from '@renderer/model/chat-history';
import { DEFAULT_LAYOUT } from '@renderer/model/layout';
import type { Schema } from '@renderer/model/types';
import { describe, expect, it } from 'vitest';

const irPath = '/work/garden.contexture.json';
const sampleIR: Schema = {
  version: '1',
  types: [{ kind: 'object', name: 'Plot', fields: [] }],
};

describe('buildSaveBundle', () => {
  it('emits five files with the expected sibling paths for a .contexture.json source', () => {
    const bundle = buildSaveBundle({
      irPath,
      schema: sampleIR,
      layout: DEFAULT_LAYOUT,
      chat: DEFAULT_CHAT_HISTORY,
    });

    const paths = bundle.files.map((f) => f.path).sort();
    expect(paths).toEqual(
      [
        '/work/garden.contexture.json',
        '/work/garden.contexture.layout.json',
        '/work/garden.contexture.chat.json',
        '/work/garden.schema.ts',
        '/work/garden.schema.json',
      ].sort(),
    );
  });

  it('emits generated .schema.ts and .schema.json with a "do not edit" header', () => {
    const bundle = buildSaveBundle({
      irPath,
      schema: sampleIR,
      layout: DEFAULT_LAYOUT,
      chat: DEFAULT_CHAT_HISTORY,
    });
    const schemaTs = bundle.files.find((f) => f.path.endsWith('.schema.ts'));
    const schemaJson = bundle.files.find((f) => f.path.endsWith('.schema.json'));
    expect(schemaTs?.content).toMatch(/Generated by Contexture.*Do not edit\./);
    expect(schemaJson?.content).toMatch(/Generated by Contexture.*Do not edit\./);
  });

  it('round-trips IR and sidecars verbatim in the bundle', () => {
    const layout = { version: '1' as const, positions: { Plot: { x: 1, y: 2 } } };
    const chat = {
      version: '1' as const,
      messages: [{ id: 'm', role: 'user' as const, content: 'hi', createdAt: 1 }],
    };
    const bundle = buildSaveBundle({ irPath, schema: sampleIR, layout, chat });
    const ir = bundle.files.find((f) => f.path.endsWith('.contexture.json'));
    const layoutFile = bundle.files.find((f) => f.path.endsWith('.contexture.layout.json'));
    const chatFile = bundle.files.find((f) => f.path.endsWith('.contexture.chat.json'));
    expect(JSON.parse(ir?.content ?? '')).toEqual(sampleIR);
    expect(JSON.parse(layoutFile?.content ?? '')).toEqual(layout);
    expect(JSON.parse(chatFile?.content ?? '')).toEqual(chat);
  });

  it('rejects an irPath that is not a .contexture.json file', () => {
    expect(() =>
      buildSaveBundle({
        irPath: '/work/garden.json',
        schema: sampleIR,
        layout: DEFAULT_LAYOUT,
        chat: DEFAULT_CHAT_HISTORY,
      }),
    ).toThrow(/\.contexture\.json/);
  });
});
