import { emit } from '@renderer/model/emit-zod';
import type { Schema } from '@renderer/model/types';
import { describe, expect, it } from 'vitest';

describe('emit (Zod)', () => {
  it('snapshot: representative IR covering all 4 TypeDef kinds and all 8 FieldType kinds', () => {
    const schema: Schema = {
      version: '1',
      imports: [
        { kind: 'stdlib', path: '@contexture/common', alias: 'common' },
        { kind: 'relative', path: './other.contexture.json', alias: 'other' },
      ],
      types: [
        {
          kind: 'object',
          name: 'Post',
          fields: [
            { name: 'title', type: { kind: 'string', min: 1, max: 120 } },
            { name: 'views', type: { kind: 'number', int: true, min: 0 } },
            { name: 'published', type: { kind: 'boolean' }, default: false },
            { name: 'createdAt', type: { kind: 'date' } },
            { name: 'kind', type: { kind: 'literal', value: 'post' } },
            { name: 'author', type: { kind: 'ref', typeName: 'common.Email' } },
            { name: 'linked', type: { kind: 'ref', typeName: 'other.Ref' } },
            {
              name: 'tags',
              optional: true,
              type: { kind: 'array', element: { kind: 'string' } },
            },
          ],
        },
        {
          kind: 'enum',
          name: 'Role',
          values: [{ value: 'admin' }, { value: 'member' }],
        },
        {
          kind: 'object',
          name: 'Click',
          fields: [
            { name: 'type', type: { kind: 'literal', value: 'click' } },
            { name: 'x', type: { kind: 'number' } },
          ],
        },
        {
          kind: 'object',
          name: 'Hover',
          fields: [
            { name: 'type', type: { kind: 'literal', value: 'hover' } },
            { name: 'target', type: { kind: 'string' } },
          ],
        },
        {
          kind: 'discriminatedUnion',
          name: 'Event',
          discriminator: 'type',
          variants: ['Click', 'Hover'],
        },
        {
          kind: 'raw',
          name: 'Money',
          zod: `z.object({ amount: z.number(), currency: z.string().length(3) })`,
          jsonSchema: {},
        },
      ],
    };
    expect(emit(schema, 'blog.contexture.json')).toMatchInlineSnapshot(`
      "// Generated by Contexture from blog.contexture.json. Do not edit.
      import { z } from 'zod';
      import { Email } from '@contexture/runtime/common';
      import { Ref } from './other.schema';

      export const Post = z.object({
        title: z.string().min(1).max(120),
        views: z.number().int().min(0),
        published: z.boolean().default(false),
        createdAt: z.date(),
        kind: z.literal('post'),
        author: Email,
        linked: Ref,
        tags: z.array(z.string()).optional(),
      });
      export type Post = z.infer<typeof Post>;

      export const Role = z.enum(['admin', 'member']);
      export type Role = z.infer<typeof Role>;

      export const Click = z.object({
        type: z.literal('click'),
        x: z.number(),
      });
      export type Click = z.infer<typeof Click>;

      export const Hover = z.object({
        type: z.literal('hover'),
        target: z.string(),
      });
      export type Hover = z.infer<typeof Hover>;

      export const Event = z.discriminatedUnion('type', [Click, Hover]);
      export type Event = z.infer<typeof Event>;

      export const Money = z.object({ amount: z.number(), currency: z.string().length(3) });
      export type Money = z.infer<typeof Money>;
      "
    `);
  });

  it('emits the generated-file header and a Zod import for an empty schema', () => {
    const schema: Schema = { version: '1', types: [] };
    const src = emit(schema, 'blog.contexture.json');
    expect(src).toBe(
      `// Generated by Contexture from blog.contexture.json. Do not edit.\nimport { z } from 'zod';\n`,
    );
  });

  it('emits literal field values (string / number / boolean)', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Tag',
          fields: [
            { name: 'kind', type: { kind: 'literal', value: 'click' } },
            { name: 'n', type: { kind: 'literal', value: 42 } },
            { name: 'b', type: { kind: 'literal', value: true } },
          ],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`kind: z.literal('click'),`);
    expect(src).toContain(`n: z.literal(42),`);
    expect(src).toContain(`b: z.literal(true),`);
  });

  it('emits array fields with nested element and min/max', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Bag',
          fields: [
            { name: 'tags', type: { kind: 'array', element: { kind: 'string' } } },
            {
              name: 'scores',
              type: { kind: 'array', element: { kind: 'number' }, min: 1, max: 5 },
            },
            {
              name: 'matrix',
              type: {
                kind: 'array',
                element: { kind: 'array', element: { kind: 'number' } },
              },
            },
          ],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`tags: z.array(z.string()),`);
    expect(src).toContain(`scores: z.array(z.number()).min(1).max(5),`);
    expect(src).toContain(`matrix: z.array(z.array(z.number())),`);
  });

  it('applies field modifiers: optional / nullable / default', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Post',
          fields: [
            { name: 'title', type: { kind: 'string' } },
            { name: 'subtitle', type: { kind: 'string' }, optional: true },
            { name: 'slug', type: { kind: 'string' }, nullable: true },
            { name: 'draft', type: { kind: 'boolean' }, default: false },
          ],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`subtitle: z.string().optional(),`);
    expect(src).toContain(`slug: z.string().nullable(),`);
    expect(src).toContain(`draft: z.boolean().default(false),`);
  });

  it('emits a local ref as a bare identifier', () => {
    const schema: Schema = {
      version: '1',
      types: [
        { kind: 'object', name: 'Post', fields: [] },
        {
          kind: 'object',
          name: 'Comment',
          fields: [{ name: 'on', type: { kind: 'ref', typeName: 'Post' } }],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`on: Post,`);
  });

  it('emits an import for a stdlib qualified ref and uses the bare name', () => {
    const schema: Schema = {
      version: '1',
      imports: [{ kind: 'stdlib', path: '@contexture/common', alias: 'common' }],
      types: [
        {
          kind: 'object',
          name: 'Contact',
          fields: [{ name: 'email', type: { kind: 'ref', typeName: 'common.Email' } }],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`import { Email } from '@contexture/runtime/common';`);
    expect(src).toContain(`email: Email,`);
  });

  it('emits an import for a relative qualified ref using the <alias>.schema path', () => {
    const schema: Schema = {
      version: '1',
      imports: [{ kind: 'relative', path: './other.contexture.json', alias: 'other' }],
      types: [
        {
          kind: 'object',
          name: 'Link',
          fields: [{ name: 'ref', type: { kind: 'ref', typeName: 'other.Post' } }],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`import { Post } from './other.schema';`);
    expect(src).toContain(`ref: Post,`);
  });

  it('emits an enum TypeDef as z.enum with exported TS type', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'enum',
          name: 'Role',
          values: [{ value: 'admin' }, { value: 'member' }],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`export const Role = z.enum(['admin', 'member']);`);
    expect(src).toContain(`export type Role = z.infer<typeof Role>;`);
  });

  it('emits a discriminatedUnion TypeDef referencing its variants', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Click',
          fields: [
            { name: 'type', type: { kind: 'literal', value: 'click' } },
            { name: 'x', type: { kind: 'number' } },
          ],
        },
        {
          kind: 'object',
          name: 'Hover',
          fields: [
            { name: 'type', type: { kind: 'literal', value: 'hover' } },
            { name: 'target', type: { kind: 'string' } },
          ],
        },
        {
          kind: 'discriminatedUnion',
          name: 'Event',
          discriminator: 'type',
          variants: ['Click', 'Hover'],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`export const Event = z.discriminatedUnion('type', [Click, Hover]);`);
    expect(src).toContain(`export type Event = z.infer<typeof Event>;`);
  });

  it('emits a raw TypeDef inline when no external import hint is given', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'raw',
          name: 'Money',
          zod: `z.object({ amount: z.number(), currency: z.string().length(3) })`,
          jsonSchema: {},
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(
      `export const Money = z.object({ amount: z.number(), currency: z.string().length(3) });`,
    );
    expect(src).toContain(`export type Money = z.infer<typeof Money>;`);
  });

  it('emits a raw TypeDef as a re-export when an external import hint is given', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'raw',
          name: 'Money',
          zod: 'Money',
          jsonSchema: {},
          import: { from: '@acme/money', name: 'Money' },
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`import { Money } from '@acme/money';`);
    expect(src).toContain(`export { Money };`);
    expect(src).toContain(`export type Money = z.infer<typeof Money>;`);
  });

  it('emits string constraints: min / max / regex / format', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Profile',
          fields: [
            { name: 'handle', type: { kind: 'string', min: 3, max: 20 } },
            { name: 'slug', type: { kind: 'string', regex: '^[a-z]+$' } },
            { name: 'email', type: { kind: 'string', format: 'email' } },
            { name: 'site', type: { kind: 'string', format: 'url' } },
            { name: 'id', type: { kind: 'string', format: 'uuid' } },
            { name: 'at', type: { kind: 'string', format: 'datetime' } },
          ],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`handle: z.string().min(3).max(20),`);
    expect(src).toContain(`slug: z.string().regex(/^[a-z]+$/),`);
    expect(src).toContain(`email: z.string().email(),`);
    expect(src).toContain(`site: z.string().url(),`);
    expect(src).toContain(`id: z.string().uuid(),`);
    expect(src).toContain(`at: z.string().datetime(),`);
  });

  it('emits number constraints: min / max / int', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Stats',
          fields: [
            { name: 'count', type: { kind: 'number', int: true, min: 0 } },
            { name: 'ratio', type: { kind: 'number', min: 0, max: 1 } },
          ],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`count: z.number().int().min(0),`);
    expect(src).toContain(`ratio: z.number().min(0).max(1),`);
  });

  it('emits primitive fields: string / number / boolean / date', () => {
    const schema: Schema = {
      version: '1',
      types: [
        {
          kind: 'object',
          name: 'Post',
          fields: [
            { name: 'title', type: { kind: 'string' } },
            { name: 'views', type: { kind: 'number' } },
            { name: 'published', type: { kind: 'boolean' } },
            { name: 'createdAt', type: { kind: 'date' } },
          ],
        },
      ],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(
      `export const Post = z.object({\n` +
        `  title: z.string(),\n` +
        `  views: z.number(),\n` +
        `  published: z.boolean(),\n` +
        `  createdAt: z.date(),\n` +
        `});`,
    );
  });

  it('emits an object TypeDef as a named z.object with an inferred TS type', () => {
    const schema: Schema = {
      version: '1',
      types: [{ kind: 'object', name: 'User', fields: [] }],
    };
    const src = emit(schema, 'x.contexture.json');
    expect(src).toContain(`export const User = z.object({});`);
    expect(src).toContain(`export type User = z.infer<typeof User>;`);
  });
});
